scrooge: Add line positions for type errors
Problem

Scrooge type errors do not show symbol position.

Solution

Annotate AST nodes with line position (RegexParsers.positioned).

Result

com.twitter.scrooge.frontend.FileParseException: Exception parsing: ./scrooge-generator/src/test/thrift/airport/bird.thrift
com.twitter.scrooge.frontend.FileParseException: Exception parsing: ./scrooge-generator/src/test/thrift/airport/bird.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: airport.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: location.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.TypeMismatchException: Type mismatch: Expecting TI32, found name: TString
    2: i32 index  = name

                    ^
	at com.twitter.scrooge.frontend.TypeResolver.apply(TypeResolver.scala:240)
    [...stacktrace...]

RB_ID=678514