scrooge: Include filenames in exception messages
Problem

Scrooge exception messages do not include thrift filenames in some cases.

Solution

- Wrap the main loop in a try/catch.
- Add try/catch blocks around recursive calls for included files in ThriftParser and TypeResolver.

Result

More readable errors:

com.twitter.scrooge.frontend.FileParseException: Exception parsing: ./scrooge-generator/src/test/thrift/airport/bird.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: airport.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.FileParseException: Exception parsing: location.thrift
	at com.twitter.util.NoStacktrace(Unknown Source)
Caused by: com.twitter.scrooge.frontend.UndefinedConstantException: asdf
    [...Stack trace...]

RB_ID=677502